### ISSUE TITLE
Make it auto-update from rsync mirror, but without unconditionally overwriting full contents

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-data-archive#2]
The idea is to sync XML files via the mirror, but avoid affecting the sidecar YAML files.

Sidecar YAML files will be added, describing docid mappings. They will be named exactly after their XML files, and be placed alongside as siblings within the same directory.

Generally, a sync should not result in those YAML files being deleted, because this repository will become more or less the authoritative source of that data (and it can be altered by hand).

(Although, if after a sync an XML file is *deleted*, YAML sidecar file *can* also be deleted. This is optional, orphaned sidecar metadata will not break anything and such cleanup can be done separately if needed.)

I think we can keep the GHA workflow that does the rsync within this repo, similar to relaton-data repositories.

**Comment by ronaldtse** [comment]
@strogonoff the rsync activities from xml2rfc.tools.ietf.org have stopped a while ago as planned. From what I understand, that site is scheduled for decomminssioning.

> because this repository will become more or less the authoritative source of that data (and it can be altered by hand).

In the new architecture, the bibxml-data-archive repository is no longer synced as it is now the authoritative data source for these entries. If IETF wishes to add other static entries, they would enter them in this repository.

**Comment by strogonoff** [comment]
Understood, thanks!
